# Generated by Django 5.2.1 on 2026-04-29 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0004_courseenrollment_services_co_user_id_9a3e17_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='bookings_ap_job_id_389830_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='bookings_ap_user_id_bc5302_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_at'], name='bookings_ap_applied_fe3898_idx'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['user'], name='bookings_sa_user_id_f206d7_idx'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['job'], name='bookings_sa_job_id_ed3e77_idx'),
        ),
    ]
