# Generated by GitHub Copilot to add internship application support

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_application_bookings_ap_job_id_389830_idx_and_more"),
        ("services", "0004_courseenrollment_services_co_user_id_9a3e17_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to="services.job",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="internship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internship_applications",
                to="services.internship",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["internship"], name="bookings_ap_internship_id_9a3e17_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("job", "user"), ("internship", "user")},
        ),
    ]
