# Generated by GitHub Copilot to allow internship-only applications

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_application_internship_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to="services.job",
            ),
        ),
    ]
