# Generated by Django 5.2.13 on 2026-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_fix_application_job_nullability'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='bookings_ap_interns_65c49f_idx',
            old_name='bookings_ap_internship_id_9a3e17_idx',
        ),
        migrations.AddField(
            model_name='application',
            name='interview_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
