# Generated by Django 5.2.1 on 2026-04-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_production_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='accounts_ot_email_c95610_idx',
            old_name='accounts_ot_email_e8af37_idx',
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='accounts_ot_phone_1f74dd_idx',
            old_name='accounts_ot_phone_93dd2f_idx',
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='accounts_ot_otp_aeeaf0_idx',
            old_name='accounts_ot_otp_5a6af9_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_token_861566_idx',
            old_name='accounts_pa_token_53d78d_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_user_id_8cd138_idx',
            old_name='accounts_pa_user_i_fce444_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_email_74c8d6_idx',
            old_name='accounts_us_email_14d0e2_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_1fa9a5_idx',
            old_name='accounts_us_role_42bd80_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_subscri_cdf94d_idx',
            old_name='accounts_us_subscr_36b03f_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_is_veri_fa45d6_idx',
            old_name='accounts_us_is_ver_456dad_idx',
        ),
    ]
