# Generated by Django 5.2.1 on 2026-05-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_change_type',
            field=models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], help_text='Type of pending subscription change', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_plan_id',
            field=models.IntegerField(blank=True, help_text='ID of plan to change to after current expires', null=True),
        ),
    ]
