from django.urls import path

from services.views import (
    AdminCourseDetailView,
    AdminCoursesView,
    AdminInternshipDetailView,
    AdminInternshipsView,
    AdminJobDetailView,
    AdminJobsView,
    AdminPlanDetailView,
    AdminPlanStatusView,
    AdminPlanSyncView,
    AdminPlansView,
    InternshipDetailView,
    InternshipsView,
    AssessmentResultView,
    AssessmentStartView,
    AssessmentSubmitView,
    AssessmentsView,
    CampaignDetailView,
    CampaignsView,
    CollegeDetailView,
    CollegesView,
    CompaniesListView,
    CourseProgressView,
    CoursesView,
    DashboardStatsView,
    EnrolledCoursesView,
    EventDetailView,
    EventRegisterView,
    EventRegistrationsView,
    EventUnregisterView,
    EventsView,
    InterviewCancelView,
    InterviewRescheduleView,
    InterviewsView,
    JobDetailView,
    JobsView,
    NotificationDeleteView,
    NotificationPreferenceView,
    NotificationReadView,
    NotificationsReadAllView,
    NotificationsView,
    PlansView,
    ServicesListView,
    StudentDetailView,
    StudentsView,
    SubscriptionStatusView,
    WebinarDetailView,
    WebinarPreferenceView,
    WebinarRegisterView,
    WebinarRegistrationsByWebinarView,
    WebinarRegistrationsView,
    WebinarUnregisterView,
    WebinarsView,
)

urlpatterns = [
    path("services", ServicesListView.as_view()),
    path("companies", CompaniesListView.as_view()),
    path("jobs", JobsView.as_view()),
    path("jobs/", JobsView.as_view()),
    path("jobs/<int:job_id>", JobDetailView.as_view()),
    path("plans", PlansView.as_view()),
    path("plans/", PlansView.as_view()),
    path("dashboard/stats", DashboardStatsView.as_view()),
    path("students", StudentsView.as_view()),
    path("students/<int:student_id>", StudentDetailView.as_view()),
    path("admin/campaigns", CampaignsView.as_view()),
    path("admin/campaigns/<int:campaign_id>", CampaignDetailView.as_view()),
    path("admin/colleges", CollegesView.as_view()),
    path("admin/colleges/<int:college_id>", CollegeDetailView.as_view()),
    path("events", EventsView.as_view()),
    path("events/", EventsView.as_view()),
    path("events/<int:event_id>", EventDetailView.as_view()),
    path("events/<int:event_id>/register", EventRegisterView.as_view()),
    path("events/<int:event_id>/unregister", EventUnregisterView.as_view()),
    path("events/registrations/<int:user_id>", EventRegistrationsView.as_view()),
    path("admin/plans", AdminPlansView.as_view()),
    path("admin/plans/<int:plan_id>", AdminPlanDetailView.as_view()),
    path("admin/plans/<int:plan_id>/status", AdminPlanStatusView.as_view()),
    path("admin/plans/<int:plan_id>/sync", AdminPlanSyncView.as_view()),
    path("admin/jobs", AdminJobsView.as_view()),
    path("admin/jobs/<int:job_id>", AdminJobDetailView.as_view()),
    path("internships", InternshipsView.as_view()),
    path("internships/", InternshipsView.as_view()),
    path("internships/<int:internship_id>", InternshipDetailView.as_view()),
    path("admin/internships", AdminInternshipsView.as_view()),
    path("admin/internships/<int:internship_id>", AdminInternshipDetailView.as_view()),
    path("notifications", NotificationsView.as_view()),
    path("notifications/<int:notification_id>/read", NotificationReadView.as_view()),
    path("notifications/read-all", NotificationsReadAllView.as_view()),
    path("notifications/<int:notification_id>", NotificationDeleteView.as_view()),
    path("notifications/preferences/<int:user_id>", NotificationPreferenceView.as_view()),
    path("webinars", WebinarsView.as_view()),
    path("webinars/<int:webinar_id>", WebinarDetailView.as_view()),
    path("webinars/<int:webinar_id>/register", WebinarRegisterView.as_view()),
    path("webinars/<int:webinar_id>/unregister", WebinarUnregisterView.as_view()),
    path("webinars/<int:webinar_id>/registrations", WebinarRegistrationsByWebinarView.as_view()),
    path("webinars/registrations/<int:user_id>", WebinarRegistrationsView.as_view()),
    path("webinars/preferences/<int:user_id>", WebinarPreferenceView.as_view()),
    path("courses", CoursesView.as_view()),
    path("admin/courses", AdminCoursesView.as_view()),
    path("admin/courses/<int:course_id>", AdminCourseDetailView.as_view()),
    path("courses/enrolled", EnrolledCoursesView.as_view()),
    path("courses/<int:course_id>/progress", CourseProgressView.as_view()),
    path("interviews", InterviewsView.as_view()),
    path("interviews/<int:interview_id>/reschedule", InterviewRescheduleView.as_view()),
    path("interviews/<int:interview_id>", InterviewCancelView.as_view()),
    path("assessments", AssessmentsView.as_view()),
    path("assessments/<int:assessment_id>/start", AssessmentStartView.as_view()),
    path("assessments/<int:assessment_id>/submit", AssessmentSubmitView.as_view()),
    path("assessments/<int:assessment_id>/result", AssessmentResultView.as_view()),
    path("subscriptions/status/<int:user_id>", SubscriptionStatusView.as_view()),
]
