# Generated by Django 5.2.1 on 2026-04-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_production_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='contact_con_email_233940_idx',
            old_name='contact_con_email_6c6d15_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='contact_con_created_fddb83_idx',
            old_name='contact_con_create_18b34e_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='contact_lea_email_46a48d_idx',
            old_name='contact_lea_email_fc6847_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='contact_lea_status_2af133_idx',
            old_name='contact_lea_status_2e523a_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='contact_lea_source_9194a7_idx',
            old_name='contact_lea_source_9016fd_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='contact_lea_created_0c1f9c_idx',
            old_name='contact_lea_create_2e9550_idx',
        ),
    ]
