# Generated by Django 5.2.1 on 2026-04-25 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('services', '0002_eventregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in paise', max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='services.plan'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentorder'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='services.plan'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'plan')},
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_e0b1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_71e312_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_3e0999_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_a2ce56_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['razorpay_payment_id'], name='payments_pa_razorpa_ad7172_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='payments_su_user_id_058311_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', '-created_at'], name='payments_su_status_dfd168_idx'),
        ),
    ]
