# Generated by Django 5.2.1 on 2026-04-29 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_student_resume_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user'], name='services_co_user_id_9a3e17_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course'], name='services_co_course__643a87_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user'], name='services_ev_user_id_747cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event'], name='services_ev_event_i_d430d3_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['company_name'], name='services_in_company_e8dc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['status'], name='services_in_status_9892d4_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['posted_at'], name='services_in_posted__4cd249_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_by_email'], name='services_jo_posted__8398b8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company'], name='services_jo_company_763805_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='services_jo_status_a40794_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_at'], name='services_jo_posted__de28c1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='services_no_user_id_3dd67b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['read'], name='services_no_read_706fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='services_no_created_dbd809_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user'], name='services_no_user_id_5f1caa_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarregistration',
            index=models.Index(fields=['user'], name='services_we_user_id_2e744f_idx'),
        ),
        migrations.AddIndex(
            model_name='webinarregistration',
            index=models.Index(fields=['webinar'], name='services_we_webinar_ba7d20_idx'),
        ),
    ]
