# Generated by Django 5.2.1 on 2026-05-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_create_499_full_access_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tabs',
            field=models.JSONField(blank=True, default=list, help_text='Tab configuration for plan details display'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tier',
            field=models.IntegerField(default=0, help_text='Numeric tier for plan comparison (upgrade/downgrade). Higher = more premium.'),
        ),
    ]
