# Generated by Django 5.2.1 on 2026-05-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_plan_tabs_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, help_text='Final price = base + fee + GST', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, help_text='Calculated GST (18% of base price)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage (e.g., 18.00 for 18%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='razorpay_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, help_text='Calculated Razorpay fee (2% of base price)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='razorpay_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Razorpay fee percentage (e.g., 2.00 for 2%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base subscription price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tabs',
            field=models.JSONField(blank=True, default=list, help_text='Tab configuration for plan details display', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.IntegerField(blank=True, default=0, help_text='Numeric tier for plan comparison (upgrade/downgrade). Higher = more premium.', null=True),
        ),
    ]
