# Generated by Django on 2026-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_plan_final_price_plan_gst_amount_plan_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
